#!/bin/sh
sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width	1
bspc config window_gap		4
bspc config split_ratio		0.5
bspc config borderless_monocle	true
bspc config gapless_monocle	true
feh --bg-scale $HOME/Downloads/imporbit.png
# really fix dbus issues. bleh
export $(dbus-launch)
pkill dunst
dunst &
# ugly hack, but at least I have a mouse cursor on startup then :p
lxappearance &
#sh ~/.config/polybar/launch.sh
#nitrogen --restore &
