#!/bin/sh

sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width	1
bspc config window_gap		4
bspc config split_ratio		0.5
bspc config borderless_monocle	true
bspc config gapless_monocle	true
sh $HOME/.config/polybar/launch.sh
synclient TapButton1=1 TapButton2=3 TapButton3=2
nitrogen --restore &
